#!/usr/bin/perl -w

use strict;

$| = 1;  # don't buffer output

my $HOME     = '/home/kaleidakustikon/cache/';
my $MUP      = "/usr/local/bin/lilypond"; 
my $timidity = "/usr/local/bin/timidity";
my $lame    = "/usr/bin/lame";

############

chdir $HOME;
my $query=$ENV{'QUERY_STRING'};
my $basename=$query;
$basename =~ s/getit.*$//;
$basename =~ s/^.*\?//;
$basename =~ s/[=\&]//g;
$query    =~ s/^.*\?//;

if($query =~ m/mid$/) {
    $query =~ s/getitas=.?mid$/getitas=mid/;
}

my $xml_file = $basename . '.xml';
my $mup_file = $basename . '.ly';
my $mid_file = $basename . '.mid';
my $pdf_file = $basename . '.pdf';
my $ps_file  = $basename . '.ps';
my $svg_file = $basename . '.svg';
my $mp3_file = $basename . '.mp3';

my $lsource   = 'http://localhost/storage/mei2013/get-cards-as-lily.xq';
my $xsource   = 'http://localhost/storage/mei2013/get-cards-as-xml.xq';
my $dev_null  = '2>&1 > /dev/null';

if($query =~ m/ps$/) {
    system("GET \'$lsource\?$query\' > $mup_file");
    print "Content-Type: application/postscript\n\n";
    system("$MUP -dpaper-size=" . '\"a4landscape\"' . " --ps $mup_file " . $dev_null );
    system("cat $ps_file");
} elsif($query =~ m/pdf$/) {
    system("GET \'$lsource\?$query\' > $mup_file");
    print "Content-Type: application/pdf\n\n";
    system("$MUP -dpaper-size=" . '\"a4landscape\"' . " --pdf $mup_file " . $dev_null );
    system("cat $pdf_file");
} elsif($query =~ m/svg$/) {
    system("GET \'$lsource\?$query\' > $mup_file");
    print "Content-Type: image/svg+xml\n\n";
    system("$MUP  -dbackend=svg $mup_file  " . $dev_null );
    system("cat $svg_file");
} elsif($query =~ m/mid$/) {
    system("GET \'$lsource\?$query\' > $mup_file");
    system("$MUP -dpaper-size=" . '\"a4landscape\"' . " --pdf $mup_file  " . $dev_null);
    print "Content-Type: audio/midi\n\n";
    my $mymidfile=$mid_file;
    if(-f $mid_file . "i") {
	$mymidfile=$mid_file . "i";
    }
    system("cat " . $mymidfile);
} elsif($query =~ m/mp3$/) {
    $query =~ s/=.mp3/=mid/;
    system("GET \'$lsource\?$query\' > $mup_file");
    system("$MUP -dpaper-size=" . '\"a4landscape\"' . " --pdf $mup_file " . $dev_null);
    my $mymidfile=$mid_file;
    if(-f $mid_file . "i") {
	$mymidfile=$mid_file . "i";
    }
    system("export HOME=.; $timidity -idq -Or $mymidfile -o - | $lame  -V 7 -r - $mp3_file " . $dev_null );
    print "Content-Type: audio/mpeg\n\n";
    system("cat " . $mp3_file );
} else {
    print "Content-Type: text/xml\n\n";
    system("GET \'$xsource\?$query\' ");
}



system("rm $pdf_file $mp3_file $ps_file $mid_file* $xml_file $mup_file $svg_file 2>/dev/null")
    unless $query =~ m/keepingcache/;

