#!/usr/bin/perl -w

use strict;

$| = 1;  # don't buffer output

my $java    = 'export JAVA_HOME=/usr/java/jdk1.6.0_24/; /usr/java/jdk1.6.0_24/bin/java';
my $HOME    = '/home/kaleidakustikon/cache/';
my $SAXON   = "/home/kaleidakustikon/saxon/saxon9.jar"; #"$HOME/data/saxon/saxon9.jar";
my $MUP     = "/home/kaleidakustikon/mup-6.1/bin/mup"; # "/home/sigge/sources/mup-6.1/bin/mup"; 
my $MEI2MUP = "/home/kaleidakustikon/saxon/mei2mup-1.0.4.xsl2";
############

my $query=$ENV{'QUERY_STRING'};
my $basename=$query;
$basename =~ s/getit.*$//;
$basename =~ s/^.*\?//;
$basename =~ s/[=\&]//g;
$query    =~ s/^.*\?//;

my $midi_arg = '';
if($query =~ m/mid$/) {
    $midi_arg = '&make=midi';
}

my $xml_file = $basename . '.xml';
my $mup_file = $basename . '.mup';
my $mid_file = $basename . '.mid';
my $pdf_file = $basename . '.pdf';
my $ps_file  = $basename . '.ps';
my $source   = 'http://disdev-01.kb.dk/storage/kuhlau/card_selector.xq';

my $mime = "";

chdir($HOME);
#if(!-f $mup_file ) {
    system("GET \'$source\?$query\' > $xml_file");
    my $cmd = "$java -jar $SAXON $xml_file  $MEI2MUP > $mup_file 2> /dev/null";
    system($cmd);
#}

if($query =~ m/ps$/) {
    print "Content-Type: application/postscript\n\n";
    print `$MUP $mup_file 2> /dev/null`;
} elsif($query =~ m/pdf$/) {
    print "Content-Type: application/pdf\n\n";
    print `$MUP $mup_file | ps2pdf -sPAPERSIZE=a4 - - 2> /dev/null`;
} elsif($query =~ m/mid$/) {
    print "Content-Type: audio/midi\n\n";
    system("$MUP $mup_file -m $mid_file 2>/dev/null");
    print `cat $mid_file`;
} else {
    print "Content-Type: text/xml\n\n";
    print `cat $xml_file`;
}

system("rm $mid_file $xml_file $mup_file 2>/dev/null")

