#!/usr/bin/perl -w

use strict;

$| = 1;  # don't buffer output

#
# The setup on dcm-frontend-01.kb.dk
#

my $HOME      = '/home/kaleidakustikon/cache/';
my $MUP       = "/usr/local/bin/lilypond"; 
my $timidity  = "/usr/local/bin/timidity";
my $lame      = "/usr/bin/lame";

# This is on disdev-01
# $timidity = "/usr/bin/timidity";
# $lame     = "/usr/local/bin/lame";
###################################################################################

###################################################################################
###### The author of the lines of code below is NOT proud of any one of them ######
###### He is, however, proud of what they achieve.                           ######
###################################################################################

chdir $HOME;
my $query=$ENV{'QUERY_STRING'};
my $basename=$query;
$basename =~ s/getit.*$//;
$basename =~ s/^.*\?//;
$basename =~ s/[=\&]//g;
$query    =~ s/^.*\?//;

if($query =~ m/mid$/) {
    $query =~ s/getitas=.?mid$/getitas=mid/;
}

my $xml_file = $basename . '.xml';
my $mup_file = $basename . '.ly';
my $mid_file = $basename . '.midi';
my $pdf_file = $basename . '.pdf';
my $ps_file  = $basename . '.ps';
my $svg_file = $basename . '.svg';
my $mp3_file = $basename . '.mp3';
my $log_file = $basename . '.log';

my $host      = 'localhost';
# $host      = 'dcm-frontend-01.kb.dk';
my $lsource   = 'http://'.$host.'/dcm/kaleidakustikon/mei/get-cards-as-lily.xq';
my $xsource   = 'http://'.$host.'/dcm/kaleidakustikon/mei/get-cards-as-xml.xq';
my $dev_null  = '2> /dev/null';
$dev_null  = '2>>'.$log_file;

if($query =~ m/ps$/) {
    system("GET \'$lsource\?$query\' > $mup_file");
    print "Content-Type: application/postscript\n\n";
    system("$MUP -dpaper-size=" . '\"a4landscape\"' . " --ps $mup_file " . $dev_null );
    system("cat $ps_file");
} elsif($query =~ m/pdf$/) {
    system("GET \'$lsource\?$query\' > $mup_file");
    print "Content-Type: application/pdf\n\n";
    system("$MUP -dpaper-size=" . '\"a4landscape\"' . " --pdf $mup_file " . $dev_null );
    system("cat $pdf_file");
} elsif($query =~ m/svg$/) {
    system("GET \'$lsource\?$query\' > $mup_file");
    print "Content-Type: image/svg+xml\n\n";
    system("$MUP  -dbackend=svg $mup_file  " . $dev_null);
    system("cat $svg_file");
} elsif($query =~ m/mid$/) {
    system("GET \'$lsource\?$query\' > $mup_file");
    system("$MUP -dpaper-size=" . '\"a4landscape\"' . " --pdf $mup_file  " . $dev_null);
    print "Content-Type: audio/midi\n\n";
    system("cat " . $mid_file);
} elsif($query =~ m/mp3$/) {
    $query =~ s/=.mp3/=mid/;
    system("GET \'$lsource\?$query\' > $mup_file");
    system("$MUP -dpaper-size=" . '\"a4landscape\"' . " --pdf $mup_file " . $dev_null);
    system("export HOME=.; $timidity -idq -Or $mid_file -o - | $lame  -V 7 -r - $mp3_file " . $dev_null );
    print "Content-Type: audio/mpeg\n\n";
    system("cat " . $mp3_file );
} else {
    print "Content-Type: text/xml\n\n";
    system("GET \'$xsource\?$query\' ");
}



system("rm $log_file $pdf_file $mp3_file $ps_file $mid_file $xml_file $mup_file $svg_file 2>/dev/null") unless $query =~ m/keepingcache/;
